### ISSUE TITLE
Panic in GridNew

### ISSUE THREAD

**Issue by philhanna** [philhanna/gocrossword#54]
```
$ go run cmd/main.go
2023/03/21 00:14:44 main.go:16: Starting crossword server
2023/03/21 00:14:44 server.go:41: Serving static files from /home/saspeh/VSProjects/gocrossword/view/static
2023/03/21 00:14:44 server.go:48: Starting server on port 5053
2023/03/21 00:14:48 uimain.go:14: Entering Home
2023/03/21 00:14:52 uigrid.go:21: Entering GridNew
2023/03/21 00:14:52 server.go:3217: http: panic serving 127.0.0.1:48414: runtime error: slice bounds out of range [-1:]
goroutine 7 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1854 +0xbf
panic({0x7ca160, 0xc00001e600})
        /usr/local/go/src/runtime/panic.go:890 +0x263
github.com/philhanna/gocrossword/model.(*Grid).FromJSON(0xc0000c3628, {0xc00019a6c0, 0x230})
        /home/saspeh/VSProjects/gocrossword/model/grid_from_json.go:156 +0x140d
github.com/philhanna/gocrossword/view.GridScreen({0x880fb0?, 0xc0000f8620}, 0x7ed39e?)
        /home/saspeh/VSProjects/gocrossword/view/uigrid.go:51 +0xbd
github.com/philhanna/gocrossword/view.GridNew({0x880fb0, 0xc0000f8620}, 0xc0000fc900)
        /home/saspeh/VSProjects/gocrossword/view/uigrid.go:42 +0x285
net/http.HandlerFunc.ServeHTTP(0xc0000fc800?, {0x880fb0?, 0xc0000f8620?}, 0xc0000c39e8?)
        /usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000000180, {0x880fb0, 0xc0000f8620}, 0xc0000fc700)
        /home/saspeh/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0xc000197890?}, {0x880fb0, 0xc0000f8620}, 0xc0000fc700)
        /usr/local/go/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc0001a0510, {0x881298, 0xc0001977a0})
        /usr/local/go/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3089 +0x5ed
2023/03/21 00:14:52 uigrid.go:21: Entering GridNew
2023/03/21 00:14:52 server.go:3217: http: panic serving 127.0.0.1:48426: runtime error: slice bounds out of range [-1:]
goroutine 10 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1854 +0xbf
panic({0x7ca160, 0xc00012a060})
        /usr/local/go/src/runtime/panic.go:890 +0x263
github.com/philhanna/gocrossword/model.(*Grid).FromJSON(0xc0000ad628, {0xc000152240, 0x230})
        /home/saspeh/VSProjects/gocrossword/model/grid_from_json.go:156 +0x140d
github.com/philhanna/gocrossword/view.GridScreen({0x880fb0?, 0xc000134000}, 0x7ed39e?)
        /home/saspeh/VSProjects/gocrossword/view/uigrid.go:51 +0xbd
github.com/philhanna/gocrossword/view.GridNew({0x880fb0, 0xc000134000}, 0xc00011c200)
        /home/saspeh/VSProjects/gocrossword/view/uigrid.go:42 +0x285
net/http.HandlerFunc.ServeHTTP(0xc00011c100?, {0x880fb0?, 0xc000134000?}, 0x800?)
        /usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000000180, {0x880fb0, 0xc000134000}, 0xc00011c000)
        /home/saspeh/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0xc000110030?}, {0x880fb0, 0xc000134000}, 0xc00011c000)
        /usr/local/go/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc0001a0750, {0x881298, 0xc0001977a0})
        /usr/local/go/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3089 +0x5ed
2023/03/21 00:14:53 uigrid.go:21: Entering GridNew
2023/03/21 00:14:53 server.go:3217: http: panic serving 127.0.0.1:35256: runtime error: slice bounds out of range [-1:]
goroutine 19 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1854 +0xbf
panic({0x7ca160, 0xc00012a0d8})
        /usr/local/go/src/runtime/panic.go:890 +0x263
github.com/philhanna/gocrossword/model.(*Grid).FromJSON(0xc0000ad628, {0xc000152900, 0x230})
        /home/saspeh/VSProjects/gocrossword/model/grid_from_json.go:156 +0x140d
github.com/philhanna/gocrossword/view.GridScreen({0x880fb0?, 0xc0001342a0}, 0x7ed39e?)
        /home/saspeh/VSProjects/gocrossword/view/uigrid.go:51 +0xbd
github.com/philhanna/gocrossword/view.GridNew({0x880fb0, 0xc0001342a0}, 0xc00011c700)
        /home/saspeh/VSProjects/gocrossword/view/uigrid.go:42 +0x285
net/http.HandlerFunc.ServeHTTP(0xc00011c600?, {0x880fb0?, 0xc0001342a0?}, 0x800?)
        /usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000000180, {0x880fb0, 0xc0001342a0}, 0xc00011c500)
        /home/saspeh/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0xc0001102a0?}, {0x880fb0, 0xc0001342a0}, 0xc00011c500)
        /usr/local/go/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc000120120, {0x881298, 0xc0001977a0})
        /usr/local/go/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3089 +0x5ed
```

**Comment by philhanna** [comment]
Failing function occurs in `GridScreen` at `grid.FromJSON`:
```go
func GridScreen(w http.ResponseWriter, r *http.Request) {

	// Get the existing grid from the session
	jsonstr := session["grid"]
	grid := new(model.Grid)
	err := grid.FromJSON(jsonstr.(string))
```

**Comment by philhanna** [comment]
... while parsing black cells.
